
import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/Header'

export const metadata: Metadata = {
  title: 'VALORANT SPOTLIGHT',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className='h-screen w-screen bg-background text-font '>
        <Header />
        {children}
      </body>
    </html>
  )
}
